### ISSUE TITLE
Could you update it to current Blazor Version?

### ISSUE THREAD

**Issue by univerise** [kjeske/rudder#2]
Hi, 

I think this is a very useful pattern to follow.

Could you update it to current Blazor Version? Thanks.

**Comment by kjeske** [comment]
Hey,

Thanks, that's nice to hear.

Yes, you can expect the update very soon, in the coming days. Will keep you informed.

**Comment by kjeske** [comment]
@univerise Rudder is updated and now uses the .NET Core 3.0 RTM.
